### ISSUE TITLE
Moving Files from One Location to Another

### ISSUE THREAD

**Issue by srijuk** [thePranab/Access_OneDrive_via_Graph_API_Python#1]
Hi Pranab
I have used your code to access my onedrive. Its been very helpful and many thanks.
I have one issue, how do I move a file from one folder to another without first downloading it , uploading to the new location and deleting it from the original location. 
Appreciate your help.
Regards
Srini

**Comment by pranabdas** [comment]
Hi, I have updated with move item example https://github.com/pranabdas/Access-OneDrive-via-Microsoft-Graph-Python#move-item. Hope it works for you.

**Comment by srijuk** [comment]
Hi Pranab
Thank you for a quick reply.
Regards
